/**
 * Auto-generated Rule Registration
 *
 * DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-rule-types.ts
 * Run 'npm run generate:types' to regenerate
 *
 * Generated: 2026-01-29T16:44:53.979Z
 * Rules registered: 66
 */

import { RuleRegistry } from '../utils/rule-registry';

// Import all rule files
import { rule as settings_permission_invalid_rule_rule } from './settings/settings-permission-invalid-rule';
import { rule as settings_permission_empty_pattern_rule } from './settings/settings-permission-empty-pattern';
import { rule as settings_invalid_permission_rule } from './settings/settings-invalid-permission';
import { rule as settings_invalid_env_var_rule } from './settings/settings-invalid-env-var';
import { rule as skill_version_rule } from './skills/skill-version';
import { rule as skill_too_many_files_rule } from './skills/skill-too-many-files';
import { rule as skill_time_sensitive_content_rule } from './skills/skill-time-sensitive-content';
import { rule as skill_tags_rule } from './skills/skill-tags';
import { rule as skill_path_traversal_rule } from './skills/skill-path-traversal';
import { rule as skill_naming_inconsistent_rule } from './skills/skill-naming-inconsistent';
import { rule as skill_name_rule } from './skills/skill-name';
import { rule as skill_model_rule } from './skills/skill-model';
import { rule as skill_missing_version_rule } from './skills/skill-missing-version';
import { rule as skill_missing_shebang_rule } from './skills/skill-missing-shebang';
import { rule as skill_missing_examples_rule } from './skills/skill-missing-examples';
import { rule as skill_missing_comments_rule } from './skills/skill-missing-comments';
import { rule as skill_missing_changelog_rule } from './skills/skill-missing-changelog';
import { rule as skill_large_reference_no_toc_rule } from './skills/skill-large-reference-no-toc';
import { rule as skill_eval_usage_rule } from './skills/skill-eval-usage';
import { rule as skill_disallowed_tools_rule } from './skills/skill-disallowed-tools';
import { rule as skill_description_rule } from './skills/skill-description';
import { rule as skill_dependencies_rule } from './skills/skill-dependencies';
import { rule as skill_deep_nesting_rule } from './skills/skill-deep-nesting';
import { rule as skill_dangerous_command_rule } from './skills/skill-dangerous-command';
import { rule as skill_context_rule } from './skills/skill-context';
import { rule as skill_body_too_long_rule } from './skills/skill-body-too-long';
import { rule as skill_allowed_tools_rule } from './skills/skill-allowed-tools';
import { rule as skill_agent_rule } from './skills/skill-agent';
import { rule as plugin_missing_file_rule } from './plugin/plugin-missing-file';
import { rule as plugin_invalid_version_rule } from './plugin/plugin-invalid-version';
import { rule as plugin_invalid_manifest_rule } from './plugin/plugin-invalid-manifest';
import { rule as plugin_dependency_invalid_version_rule } from './plugin/plugin-dependency-invalid-version';
import { rule as plugin_circular_dependency_rule } from './plugin/plugin-circular-dependency';
import { rule as commands_in_plugin_deprecated_rule } from './plugin/commands-in-plugin-deprecated';
import { rule as output_style_name_rule } from './output-styles/output-style-name';
import { rule as output_style_examples_rule } from './output-styles/output-style-examples';
import { rule as output_style_description_rule } from './output-styles/output-style-description';
import { rule as hooks_missing_script_rule } from './hooks/hooks-missing-script';
import { rule as hooks_invalid_event_rule } from './hooks/hooks-invalid-event';
import { rule as hooks_invalid_config_rule } from './hooks/hooks-invalid-config';
import { rule as mcp_invalid_transport_rule } from './mcp/mcp-invalid-transport';
import { rule as mcp_invalid_server_rule } from './mcp/mcp-invalid-server';
import { rule as mcp_invalid_env_var_rule } from './mcp/mcp-invalid-env-var';
import { rule as commands_migrate_to_skills_rule } from './commands/commands-migrate-to-skills';
import { rule as commands_deprecated_directory_rule } from './commands/commands-deprecated-directory';
import { rule as claude_md_size_warning_rule } from './claude-md/claude-md-size-warning';
import { rule as claude_md_size_error_rule } from './claude-md/claude-md-size-error';
import { rule as claude_md_rules_circular_symlink_rule } from './claude-md/claude-md-rules-circular-symlink';
import { rule as claude_md_paths_rule } from './claude-md/claude-md-paths';
import { rule as claude_md_import_missing_rule } from './claude-md/claude-md-import-missing';
import { rule as claude_md_import_in_code_block_rule } from './claude-md/claude-md-import-in-code-block';
import { rule as claude_md_import_circular_rule } from './claude-md/claude-md-import-circular';
import { rule as claude_md_glob_pattern_too_broad_rule } from './claude-md/claude-md-glob-pattern-too-broad';
import { rule as claude_md_glob_pattern_backslash_rule } from './claude-md/claude-md-glob-pattern-backslash';
import { rule as claude_md_filename_case_sensitive_rule } from './claude-md/claude-md-filename-case-sensitive';
import { rule as claude_md_content_too_many_sections_rule } from './claude-md/claude-md-content-too-many-sections';
import { rule as agent_tools_rule } from './agents/agent-tools';
import { rule as agent_skills_rule } from './agents/agent-skills';
import { rule as agent_skills_not_found_rule } from './agents/agent-skills-not-found';
import { rule as agent_name_rule } from './agents/agent-name';
import { rule as agent_model_rule } from './agents/agent-model';
import { rule as agent_hooks_rule } from './agents/agent-hooks';
import { rule as agent_hooks_invalid_schema_rule } from './agents/agent-hooks-invalid-schema';
import { rule as agent_events_rule } from './agents/agent-events';
import { rule as agent_disallowed_tools_rule } from './agents/agent-disallowed-tools';
import { rule as agent_description_rule } from './agents/agent-description';

// Register all rules with the registry
// This happens automatically when this module is imported
  RuleRegistry.register(settings_permission_invalid_rule_rule);
  RuleRegistry.register(settings_permission_empty_pattern_rule);
  RuleRegistry.register(settings_invalid_permission_rule);
  RuleRegistry.register(settings_invalid_env_var_rule);
  RuleRegistry.register(skill_version_rule);
  RuleRegistry.register(skill_too_many_files_rule);
  RuleRegistry.register(skill_time_sensitive_content_rule);
  RuleRegistry.register(skill_tags_rule);
  RuleRegistry.register(skill_path_traversal_rule);
  RuleRegistry.register(skill_naming_inconsistent_rule);
  RuleRegistry.register(skill_name_rule);
  RuleRegistry.register(skill_model_rule);
  RuleRegistry.register(skill_missing_version_rule);
  RuleRegistry.register(skill_missing_shebang_rule);
  RuleRegistry.register(skill_missing_examples_rule);
  RuleRegistry.register(skill_missing_comments_rule);
  RuleRegistry.register(skill_missing_changelog_rule);
  RuleRegistry.register(skill_large_reference_no_toc_rule);
  RuleRegistry.register(skill_eval_usage_rule);
  RuleRegistry.register(skill_disallowed_tools_rule);
  RuleRegistry.register(skill_description_rule);
  RuleRegistry.register(skill_dependencies_rule);
  RuleRegistry.register(skill_deep_nesting_rule);
  RuleRegistry.register(skill_dangerous_command_rule);
  RuleRegistry.register(skill_context_rule);
  RuleRegistry.register(skill_body_too_long_rule);
  RuleRegistry.register(skill_allowed_tools_rule);
  RuleRegistry.register(skill_agent_rule);
  RuleRegistry.register(plugin_missing_file_rule);
  RuleRegistry.register(plugin_invalid_version_rule);
  RuleRegistry.register(plugin_invalid_manifest_rule);
  RuleRegistry.register(plugin_dependency_invalid_version_rule);
  RuleRegistry.register(plugin_circular_dependency_rule);
  RuleRegistry.register(commands_in_plugin_deprecated_rule);
  RuleRegistry.register(output_style_name_rule);
  RuleRegistry.register(output_style_examples_rule);
  RuleRegistry.register(output_style_description_rule);
  RuleRegistry.register(hooks_missing_script_rule);
  RuleRegistry.register(hooks_invalid_event_rule);
  RuleRegistry.register(hooks_invalid_config_rule);
  RuleRegistry.register(mcp_invalid_transport_rule);
  RuleRegistry.register(mcp_invalid_server_rule);
  RuleRegistry.register(mcp_invalid_env_var_rule);
  RuleRegistry.register(commands_migrate_to_skills_rule);
  RuleRegistry.register(commands_deprecated_directory_rule);
  RuleRegistry.register(claude_md_size_warning_rule);
  RuleRegistry.register(claude_md_size_error_rule);
  RuleRegistry.register(claude_md_rules_circular_symlink_rule);
  RuleRegistry.register(claude_md_paths_rule);
  RuleRegistry.register(claude_md_import_missing_rule);
  RuleRegistry.register(claude_md_import_in_code_block_rule);
  RuleRegistry.register(claude_md_import_circular_rule);
  RuleRegistry.register(claude_md_glob_pattern_too_broad_rule);
  RuleRegistry.register(claude_md_glob_pattern_backslash_rule);
  RuleRegistry.register(claude_md_filename_case_sensitive_rule);
  RuleRegistry.register(claude_md_content_too_many_sections_rule);
  RuleRegistry.register(agent_tools_rule);
  RuleRegistry.register(agent_skills_rule);
  RuleRegistry.register(agent_skills_not_found_rule);
  RuleRegistry.register(agent_name_rule);
  RuleRegistry.register(agent_model_rule);
  RuleRegistry.register(agent_hooks_rule);
  RuleRegistry.register(agent_hooks_invalid_schema_rule);
  RuleRegistry.register(agent_events_rule);
  RuleRegistry.register(agent_disallowed_tools_rule);
  RuleRegistry.register(agent_description_rule);

// Export all rules for direct access if needed
export {
  settings_permission_invalid_rule_rule,
  settings_permission_empty_pattern_rule,
  settings_invalid_permission_rule,
  settings_invalid_env_var_rule,
  skill_version_rule,
  skill_too_many_files_rule,
  skill_time_sensitive_content_rule,
  skill_tags_rule,
  skill_path_traversal_rule,
  skill_naming_inconsistent_rule,
  skill_name_rule,
  skill_model_rule,
  skill_missing_version_rule,
  skill_missing_shebang_rule,
  skill_missing_examples_rule,
  skill_missing_comments_rule,
  skill_missing_changelog_rule,
  skill_large_reference_no_toc_rule,
  skill_eval_usage_rule,
  skill_disallowed_tools_rule,
  skill_description_rule,
  skill_dependencies_rule,
  skill_deep_nesting_rule,
  skill_dangerous_command_rule,
  skill_context_rule,
  skill_body_too_long_rule,
  skill_allowed_tools_rule,
  skill_agent_rule,
  plugin_missing_file_rule,
  plugin_invalid_version_rule,
  plugin_invalid_manifest_rule,
  plugin_dependency_invalid_version_rule,
  plugin_circular_dependency_rule,
  commands_in_plugin_deprecated_rule,
  output_style_name_rule,
  output_style_examples_rule,
  output_style_description_rule,
  hooks_missing_script_rule,
  hooks_invalid_event_rule,
  hooks_invalid_config_rule,
  mcp_invalid_transport_rule,
  mcp_invalid_server_rule,
  mcp_invalid_env_var_rule,
  commands_migrate_to_skills_rule,
  commands_deprecated_directory_rule,
  claude_md_size_warning_rule,
  claude_md_size_error_rule,
  claude_md_rules_circular_symlink_rule,
  claude_md_paths_rule,
  claude_md_import_missing_rule,
  claude_md_import_in_code_block_rule,
  claude_md_import_circular_rule,
  claude_md_glob_pattern_too_broad_rule,
  claude_md_glob_pattern_backslash_rule,
  claude_md_filename_case_sensitive_rule,
  claude_md_content_too_many_sections_rule,
  agent_tools_rule,
  agent_skills_rule,
  agent_skills_not_found_rule,
  agent_name_rule,
  agent_model_rule,
  agent_hooks_rule,
  agent_hooks_invalid_schema_rule,
  agent_events_rule,
  agent_disallowed_tools_rule,
  agent_description_rule,
};
