/**
 * Auto-generated Rule IDs
 *
 * DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-rule-types.ts
 * Run 'npm run generate:types' to regenerate
 *
 * Generated: 2026-01-29T05:07:52.429Z
 * Rule count: 66
 */

/**
 * Union of all rule IDs
 *
 * This type is automatically generated from discovered rule files.
 * Each rule file in src/rules/**\/*.ts becomes a valid RuleId.
 *
 * NOTE: Some rules (cross-file validation) have their validation logic
 * implemented in validators rather than in their validate() function,
 * as they require stateful context across multiple files.
 */
export type RuleId =
  | 'agent-description'
  | 'agent-disallowed-tools'
  | 'agent-events'
  | 'agent-hooks'
  | 'agent-hooks-invalid-schema'
  | 'agent-model'
  | 'agent-name'
  | 'agent-skills'
  | 'agent-skills-not-found'
  | 'agent-tools'
  | 'claude-md-content-too-many-sections'
  | 'claude-md-filename-case-sensitive'
  | 'claude-md-glob-pattern-backslash'
  | 'claude-md-glob-pattern-too-broad'
  | 'claude-md-import-circular'
  | 'claude-md-import-in-code-block'
  | 'claude-md-import-missing'
  | 'claude-md-paths'
  | 'claude-md-rules-circular-symlink'
  | 'claude-md-size-error'
  | 'claude-md-size-warning'
  | 'commands-deprecated-directory'
  | 'commands-in-plugin-deprecated'
  | 'commands-migrate-to-skills'
  | 'hooks-invalid-config'
  | 'hooks-invalid-event'
  | 'hooks-missing-script'
  | 'mcp-invalid-env-var'
  | 'mcp-invalid-server'
  | 'mcp-invalid-transport'
  | 'output-style-description'
  | 'output-style-examples'
  | 'output-style-name'
  | 'plugin-circular-dependency'
  | 'plugin-dependency-invalid-version'
  | 'plugin-invalid-manifest'
  | 'plugin-invalid-version'
  | 'plugin-missing-file'
  | 'settings-invalid-env-var'
  | 'settings-invalid-permission'
  | 'settings-permission-empty-pattern'
  | 'settings-permission-invalid-rule'
  | 'skill-agent'
  | 'skill-allowed-tools'
  | 'skill-body-too-long'
  | 'skill-context'
  | 'skill-dangerous-command'
  | 'skill-deep-nesting'
  | 'skill-dependencies'
  | 'skill-description'
  | 'skill-disallowed-tools'
  | 'skill-eval-usage'
  | 'skill-large-reference-no-toc'
  | 'skill-missing-changelog'
  | 'skill-missing-comments'
  | 'skill-missing-examples'
  | 'skill-missing-shebang'
  | 'skill-missing-version'
  | 'skill-model'
  | 'skill-name'
  | 'skill-naming-inconsistent'
  | 'skill-path-traversal'
  | 'skill-tags'
  | 'skill-time-sensitive-content'
  | 'skill-too-many-files'
  | 'skill-version';

/**
 * All valid rule IDs as a readonly array
 *
 * Useful for runtime validation and iteration.
 */
export const ALL_RULE_IDS: readonly RuleId[] = [
  'agent-description',
  'agent-disallowed-tools',
  'agent-events',
  'agent-hooks',
  'agent-hooks-invalid-schema',
  'agent-model',
  'agent-name',
  'agent-skills',
  'agent-skills-not-found',
  'agent-tools',
  'claude-md-content-too-many-sections',
  'claude-md-filename-case-sensitive',
  'claude-md-glob-pattern-backslash',
  'claude-md-glob-pattern-too-broad',
  'claude-md-import-circular',
  'claude-md-import-in-code-block',
  'claude-md-import-missing',
  'claude-md-paths',
  'claude-md-rules-circular-symlink',
  'claude-md-size-error',
  'claude-md-size-warning',
  'commands-deprecated-directory',
  'commands-in-plugin-deprecated',
  'commands-migrate-to-skills',
  'hooks-invalid-config',
  'hooks-invalid-event',
  'hooks-missing-script',
  'mcp-invalid-env-var',
  'mcp-invalid-server',
  'mcp-invalid-transport',
  'output-style-description',
  'output-style-examples',
  'output-style-name',
  'plugin-circular-dependency',
  'plugin-dependency-invalid-version',
  'plugin-invalid-manifest',
  'plugin-invalid-version',
  'plugin-missing-file',
  'settings-invalid-env-var',
  'settings-invalid-permission',
  'settings-permission-empty-pattern',
  'settings-permission-invalid-rule',
  'skill-agent',
  'skill-allowed-tools',
  'skill-body-too-long',
  'skill-context',
  'skill-dangerous-command',
  'skill-deep-nesting',
  'skill-dependencies',
  'skill-description',
  'skill-disallowed-tools',
  'skill-eval-usage',
  'skill-large-reference-no-toc',
  'skill-missing-changelog',
  'skill-missing-comments',
  'skill-missing-examples',
  'skill-missing-shebang',
  'skill-missing-version',
  'skill-model',
  'skill-name',
  'skill-naming-inconsistent',
  'skill-path-traversal',
  'skill-tags',
  'skill-time-sensitive-content',
  'skill-too-many-files',
  'skill-version',
] as const;

/**
 * Type guard to check if a string is a valid RuleId
 *
 * @param value - String to check
 * @returns True if value is a valid RuleId
 *
 * @example
 * if (isRuleId(userInput)) {
 *   // TypeScript knows userInput is RuleId
 *   const rule = await ruleLoader.getRule(userInput);
 * }
 */
export function isRuleId(value: string): value is RuleId {
  return (ALL_RULE_IDS as readonly string[]).includes(value);
}
