/**
 * Auto-generated Rule IDs
 *
 * DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-rule-types.ts
 * Run 'npm run generate:types' to regenerate
 *
 * Generated: 2026-02-04T18:56:08.817Z
 * Rule count: 98
 */

/**
 * Union of all rule IDs
 *
 * This type is automatically generated from discovered rule files.
 * Each rule file in src/rules/**\/*.ts becomes a valid RuleId.
 *
 * NOTE: Some rules (cross-file validation) have their validation logic
 * implemented in validators rather than in their validate() function,
 * as they require stateful context across multiple files.
 */
export type RuleId =
  | 'agent-body-too-short'
  | 'agent-description'
  | 'agent-disallowed-tools'
  | 'agent-hooks'
  | 'agent-hooks-invalid-schema'
  | 'agent-missing-system-prompt'
  | 'agent-model'
  | 'agent-name'
  | 'agent-name-directory-mismatch'
  | 'agent-skills'
  | 'agent-skills-not-found'
  | 'agent-tools'
  | 'claude-md-content-too-many-sections'
  | 'claude-md-file-not-found'
  | 'claude-md-filename-case-sensitive'
  | 'claude-md-glob-pattern-backslash'
  | 'claude-md-glob-pattern-too-broad'
  | 'claude-md-import-circular'
  | 'claude-md-import-depth-exceeded'
  | 'claude-md-import-in-code-block'
  | 'claude-md-import-missing'
  | 'claude-md-import-read-failed'
  | 'claude-md-paths'
  | 'claude-md-rules-circular-symlink'
  | 'claude-md-size-error'
  | 'claude-md-size-warning'
  | 'commands-deprecated-directory'
  | 'commands-in-plugin-deprecated'
  | 'commands-migrate-to-skills'
  | 'hooks-invalid-config'
  | 'hooks-invalid-event'
  | 'hooks-missing-script'
  | 'lsp-command-not-in-path'
  | 'lsp-config-file-not-json'
  | 'lsp-config-file-relative-path'
  | 'lsp-extension-missing-dot'
  | 'lsp-invalid-transport'
  | 'lsp-language-id-empty'
  | 'lsp-language-id-not-lowercase'
  | 'lsp-server-name-too-short'
  | 'mcp-http-empty-url'
  | 'mcp-http-invalid-url'
  | 'mcp-invalid-env-var'
  | 'mcp-invalid-server'
  | 'mcp-invalid-transport'
  | 'mcp-server-key-mismatch'
  | 'mcp-sse-empty-url'
  | 'mcp-sse-invalid-url'
  | 'mcp-sse-transport-deprecated'
  | 'mcp-stdio-empty-command'
  | 'mcp-websocket-empty-url'
  | 'mcp-websocket-invalid-protocol'
  | 'mcp-websocket-invalid-url'
  | 'output-style-body-too-short'
  | 'output-style-missing-guidelines'
  | 'output-style-name-directory-mismatch'
  | 'plugin-components-wrong-location'
  | 'plugin-description-required'
  | 'plugin-invalid-manifest'
  | 'plugin-invalid-version'
  | 'plugin-json-wrong-location'
  | 'plugin-marketplace-files-not-found'
  | 'plugin-missing-file'
  | 'plugin-name-required'
  | 'plugin-version-required'
  | 'settings-file-path-not-found'
  | 'settings-invalid-env-var'
  | 'settings-invalid-permission'
  | 'settings-permission-empty-pattern'
  | 'settings-permission-invalid-rule'
  | 'skill-agent'
  | 'skill-allowed-tools'
  | 'skill-body-too-long'
  | 'skill-context'
  | 'skill-dangerous-command'
  | 'skill-deep-nesting'
  | 'skill-dependencies'
  | 'skill-description'
  | 'skill-disallowed-tools'
  | 'skill-eval-usage'
  | 'skill-missing-changelog'
  | 'skill-missing-comments'
  | 'skill-missing-examples'
  | 'skill-missing-shebang'
  | 'skill-missing-version'
  | 'skill-model'
  | 'skill-multi-script-missing-readme'
  | 'skill-name'
  | 'skill-name-directory-mismatch'
  | 'skill-naming-inconsistent'
  | 'skill-overly-generic-name'
  | 'skill-path-traversal'
  | 'skill-referenced-file-not-found'
  | 'skill-tags'
  | 'skill-time-sensitive-content'
  | 'skill-too-many-files'
  | 'skill-unknown-string-substitution'
  | 'skill-version';

/**
 * All valid rule IDs as a readonly array
 *
 * Useful for runtime validation and iteration.
 */
export const ALL_RULE_IDS: readonly RuleId[] = [
  'agent-body-too-short',
  'agent-description',
  'agent-disallowed-tools',
  'agent-hooks',
  'agent-hooks-invalid-schema',
  'agent-missing-system-prompt',
  'agent-model',
  'agent-name',
  'agent-name-directory-mismatch',
  'agent-skills',
  'agent-skills-not-found',
  'agent-tools',
  'claude-md-content-too-many-sections',
  'claude-md-file-not-found',
  'claude-md-filename-case-sensitive',
  'claude-md-glob-pattern-backslash',
  'claude-md-glob-pattern-too-broad',
  'claude-md-import-circular',
  'claude-md-import-depth-exceeded',
  'claude-md-import-in-code-block',
  'claude-md-import-missing',
  'claude-md-import-read-failed',
  'claude-md-paths',
  'claude-md-rules-circular-symlink',
  'claude-md-size-error',
  'claude-md-size-warning',
  'commands-deprecated-directory',
  'commands-in-plugin-deprecated',
  'commands-migrate-to-skills',
  'hooks-invalid-config',
  'hooks-invalid-event',
  'hooks-missing-script',
  'lsp-command-not-in-path',
  'lsp-config-file-not-json',
  'lsp-config-file-relative-path',
  'lsp-extension-missing-dot',
  'lsp-invalid-transport',
  'lsp-language-id-empty',
  'lsp-language-id-not-lowercase',
  'lsp-server-name-too-short',
  'mcp-http-empty-url',
  'mcp-http-invalid-url',
  'mcp-invalid-env-var',
  'mcp-invalid-server',
  'mcp-invalid-transport',
  'mcp-server-key-mismatch',
  'mcp-sse-empty-url',
  'mcp-sse-invalid-url',
  'mcp-sse-transport-deprecated',
  'mcp-stdio-empty-command',
  'mcp-websocket-empty-url',
  'mcp-websocket-invalid-protocol',
  'mcp-websocket-invalid-url',
  'output-style-body-too-short',
  'output-style-missing-guidelines',
  'output-style-name-directory-mismatch',
  'plugin-components-wrong-location',
  'plugin-description-required',
  'plugin-invalid-manifest',
  'plugin-invalid-version',
  'plugin-json-wrong-location',
  'plugin-marketplace-files-not-found',
  'plugin-missing-file',
  'plugin-name-required',
  'plugin-version-required',
  'settings-file-path-not-found',
  'settings-invalid-env-var',
  'settings-invalid-permission',
  'settings-permission-empty-pattern',
  'settings-permission-invalid-rule',
  'skill-agent',
  'skill-allowed-tools',
  'skill-body-too-long',
  'skill-context',
  'skill-dangerous-command',
  'skill-deep-nesting',
  'skill-dependencies',
  'skill-description',
  'skill-disallowed-tools',
  'skill-eval-usage',
  'skill-missing-changelog',
  'skill-missing-comments',
  'skill-missing-examples',
  'skill-missing-shebang',
  'skill-missing-version',
  'skill-model',
  'skill-multi-script-missing-readme',
  'skill-name',
  'skill-name-directory-mismatch',
  'skill-naming-inconsistent',
  'skill-overly-generic-name',
  'skill-path-traversal',
  'skill-referenced-file-not-found',
  'skill-tags',
  'skill-time-sensitive-content',
  'skill-too-many-files',
  'skill-unknown-string-substitution',
  'skill-version',
] as const;

/**
 * Type guard to check if a string is a valid RuleId
 *
 * @param value - String to check
 * @returns True if value is a valid RuleId
 *
 * @example
 * if (isRuleId(userInput)) {
 *   // TypeScript knows userInput is RuleId
 *   const rule = await ruleLoader.getRule(userInput);
 * }
 */
export function isRuleId(value: string): value is RuleId {
  return (ALL_RULE_IDS as readonly string[]).includes(value);
}
