/**
 * Tests for settings schema
 */

import {
  SettingsSchema,
  PermissionsSchema,
  AttributionSchema,
  SandboxSchema,
  SettingsHooksSchema,
  MarketplaceConfigSchema,
} from '../../src/validators/schemas';

describe('SettingsSchema', () => {
  describe('valid configurations', () => {
    it('should accept empty settings object', () => {
      const result = SettingsSchema.safeParse({});
      expect(result.success).toBe(true);
    });

    it('should accept settings with all fields', () => {
      const result = SettingsSchema.safeParse({
        $schema: 'https://json.schemastore.org/claude-code-settings.json',
        permissions: {
          allow: ['Read'],
          deny: ['Bash(rm *)'],
          ask: ['Write'],
        },
        env: {
          NODE_ENV: 'development',
        },
        model: 'sonnet',
        apiKeyHelper: 'get-api-key.sh',
        hooks: {},
        attribution: {
          commit: 'Generated by Claude',
          pr: 'Created with Claude Code',
        },
        // An OBJECT, not a string (docs-baseline/settings.md:300). This test asserted the
        // string form, which is how the false positive stayed shipped.
        statusLine: { type: 'command', command: '~/.claude/statusline.sh' },
        outputStyle: 'concise',
        sandbox: {
          enabled: true,
        },
        enabledPlugins: {
          'my-plugin': true,
        },
        autoUpdatesChannel: 'stable',
        cleanupPeriodDays: 30,
        language: 'en',
        respectGitignore: true,
        enableAllProjectMcpServers: false,
        disableAllHooks: false,
        // A STRING enum (`in-process`, `auto`, ...), not a boolean (settings.md:304).
        teammateMode: 'auto',
        showTurnDuration: true,
        terminalProgressBarEnabled: true,
        spinnerTipsEnabled: true,
        alwaysThinkingEnabled: false,
        prefersReducedMotion: false,
        plansDirectory: '.claude/plans',
        skipWebFetchPreflight: false,
      });
      expect(result.success).toBe(true);
    });
  });

  describe('model field', () => {
    it('should accept any string for model', () => {
      const result = SettingsSchema.safeParse({
        model: 'sonnet',
      });
      expect(result.success).toBe(true);
    });

    it('should accept model aliases', () => {
      const result = SettingsSchema.safeParse({
        model: 'claude-sonnet-4-5-20250929',
      });
      expect(result.success).toBe(true);
    });

    it('should accept custom model names', () => {
      const result = SettingsSchema.safeParse({
        model: 'my-custom-model',
      });
      expect(result.success).toBe(true);
    });
  });

  describe('env field', () => {
    it('should accept env variables object', () => {
      const result = SettingsSchema.safeParse({
        env: {
          API_KEY: 'secret',
          DEBUG: 'true',
        },
      });
      expect(result.success).toBe(true);
    });

    it('should accept empty env object', () => {
      const result = SettingsSchema.safeParse({
        env: {},
      });
      expect(result.success).toBe(true);
    });
  });

  describe('enabledPlugins field', () => {
    it('should accept plugin enable/disable map', () => {
      const result = SettingsSchema.safeParse({
        enabledPlugins: {
          'plugin-a': true,
          'plugin-b': false,
          'plugin-c': true,
        },
      });
      expect(result.success).toBe(true);
    });
  });
});

describe('PermissionsSchema', () => {
  describe('permission arrays', () => {
    it('should accept allow array', () => {
      const result = PermissionsSchema.safeParse({
        allow: ['Read', 'Bash(ls)'],
      });
      expect(result.success).toBe(true);
    });

    it('should accept deny array', () => {
      const result = PermissionsSchema.safeParse({
        deny: ['Bash(rm -rf /)', 'Write(.env)'],
      });
      expect(result.success).toBe(true);
    });

    it('should accept ask array', () => {
      const result = PermissionsSchema.safeParse({
        ask: ['Write', 'Edit'],
      });
      expect(result.success).toBe(true);
    });

    it('should accept all three arrays', () => {
      const result = PermissionsSchema.safeParse({
        allow: ['Read'],
        deny: ['Bash(rm *)'],
        ask: ['Write'],
      });
      expect(result.success).toBe(true);
    });

    it('should accept empty arrays', () => {
      const result = PermissionsSchema.safeParse({
        allow: [],
        deny: [],
        ask: [],
      });
      expect(result.success).toBe(true);
    });
  });

  describe('defaultMode field', () => {
    it('should accept acceptEdits mode', () => {
      const result = PermissionsSchema.safeParse({
        defaultMode: 'acceptEdits',
      });
      expect(result.success).toBe(true);
    });

    it('should accept bypassPermissions mode', () => {
      const result = PermissionsSchema.safeParse({
        defaultMode: 'bypassPermissions',
      });
      expect(result.success).toBe(true);
    });

    it('should accept default mode', () => {
      const result = PermissionsSchema.safeParse({
        defaultMode: 'default',
      });
      expect(result.success).toBe(true);
    });

    it('should accept plan mode', () => {
      const result = PermissionsSchema.safeParse({
        defaultMode: 'plan',
      });
      expect(result.success).toBe(true);
    });

    it('should reject invalid mode', () => {
      const result = PermissionsSchema.safeParse({
        defaultMode: 'invalid',
      });
      expect(result.success).toBe(false);
    });
  });

  describe('disableBypassPermissionsMode field', () => {
    it('should accept disable value', () => {
      const result = PermissionsSchema.safeParse({
        disableBypassPermissionsMode: 'disable',
      });
      expect(result.success).toBe(true);
    });

    it('should reject other values', () => {
      const result = PermissionsSchema.safeParse({
        disableBypassPermissionsMode: 'enable',
      });
      expect(result.success).toBe(false);
    });
  });

  describe('additionalDirectories field', () => {
    it('should accept array of directory paths', () => {
      const result = PermissionsSchema.safeParse({
        additionalDirectories: ['/path/to/dir1', '/path/to/dir2'],
      });
      expect(result.success).toBe(true);
    });

    it('should accept empty array', () => {
      const result = PermissionsSchema.safeParse({
        additionalDirectories: [],
      });
      expect(result.success).toBe(true);
    });
  });
});

describe('AttributionSchema', () => {
  it('should accept commit message template', () => {
    const result = AttributionSchema.safeParse({
      commit: 'Generated by Claude',
    });
    expect(result.success).toBe(true);
  });

  it('should accept pr message template', () => {
    const result = AttributionSchema.safeParse({
      pr: 'This PR was generated with Claude Code',
    });
    expect(result.success).toBe(true);
  });

  it('should accept both commit and pr', () => {
    const result = AttributionSchema.safeParse({
      commit: 'Generated by Claude',
      pr: 'Created with Claude Code',
    });
    expect(result.success).toBe(true);
  });

  it('should accept all fields optional', () => {
    const result = AttributionSchema.safeParse({});
    expect(result.success).toBe(true);
  });
});

describe('SandboxSchema', () => {
  it('should accept enabled flag', () => {
    const result = SandboxSchema.safeParse({
      enabled: true,
    });
    expect(result.success).toBe(true);
  });

  it('should accept autoAllowBashIfSandboxed', () => {
    const result = SandboxSchema.safeParse({
      enabled: true,
      autoAllowBashIfSandboxed: true,
    });
    expect(result.success).toBe(true);
  });

  it('should accept excludedCommands array', () => {
    const result = SandboxSchema.safeParse({
      enabled: true,
      excludedCommands: ['rm', 'sudo'],
    });
    expect(result.success).toBe(true);
  });

  it('accepts allowUnsandboxedCommands as a BOOLEAN', () => {
    // Documented as a boolean: "Allow commands to run outside the sandbox via the
    // `dangerouslyDisableSandbox` parameter. When set to `false`, the escape hatch is
    // completely disabled... Default: true" (docs-baseline/settings.md).
    // It was modelled as `string[]`, so the documented usage errored with
    // "expected array, received boolean". This test asserted the wrong type.
    expect(SandboxSchema.safeParse({ allowUnsandboxedCommands: false }).success).toBe(true);
    expect(SandboxSchema.safeParse({ allowUnsandboxedCommands: ['docker'] }).success).toBe(false);
  });

  it('should accept network config with the DOCUMENTED field names', () => {
    const result = SandboxSchema.safeParse({
      enabled: true,
      network: {
        allowedDomains: ['github.com', '*.npmjs.org'],
        deniedDomains: ['sensitive.cloud.example.com'],
        httpProxyPort: 8080,
        socksProxyPort: 8081,
        allowManagedDomainsOnly: true,
      },
    });
    expect(result.success).toBe(true);
  });

  it('does not model the invented network fields', () => {
    // `allowedHosts` and `allowedPorts` were both fabricated -- the real fields are
    // `allowedDomains` and `httpProxyPort`/`socksProxyPort`. The schema is non-strict, so
    // parsing still succeeds; what must be true is that these are STRIPPED rather than
    // modelled, so claudelint never blesses a key Claude Code ignores.
    const result = SandboxSchema.parse({
      network: { allowedHosts: ['api.example.com'], allowedPorts: [443] },
    });

    expect(result.network).toEqual({});
  });

  it('does not model the invented ignoreViolations field', () => {
    // Appears nowhere in the docs.
    expect(SandboxSchema.parse({ ignoreViolations: true })).toEqual({});
  });

  it('should accept enableWeakerNestedSandbox', () => {
    // NOT a hallucination -- this one IS documented. Verified before touching it.
    const result = SandboxSchema.safeParse({
      enableWeakerNestedSandbox: true,
    });
    expect(result.success).toBe(true);
  });

  it('accepts the documented filesystem subtree', () => {
    const result = SandboxSchema.safeParse({
      filesystem: {
        allowWrite: ['/tmp/build', '~/.kube'],
        denyRead: ['~/.aws/credentials'],
        allowManagedReadPathsOnly: true,
      },
    });
    expect(result.success).toBe(true);
  });

  it('accepts the documented credentials subtree', () => {
    const result = SandboxSchema.safeParse({
      credentials: {
        files: [{ path: '~/.aws/credentials', mode: 'deny' }],
        envVars: [{ name: 'GITHUB_TOKEN', mode: 'deny' }],
        allowPlaintextInject: true,
      },
    });
    expect(result.success).toBe(true);
  });

  it('rejects an unsupported credential file mode', () => {
    // `deny` is the only supported mode for files; `mask` is env-vars-only.
    const result = SandboxSchema.safeParse({
      credentials: { files: [{ path: '~/.aws/credentials', mode: 'mask' }] },
    });
    expect(result.success).toBe(false);
  });

  it('should accept all fields optional', () => {
    const result = SandboxSchema.safeParse({});
    expect(result.success).toBe(true);
  });

  it('should accept full sandbox configuration', () => {
    const result = SandboxSchema.safeParse({
      enabled: true,
      failIfUnavailable: true,
      autoAllowBashIfSandboxed: true,
      excludedCommands: ['docker *'],
      allowUnsandboxedCommands: false,
      filesystem: { allowWrite: ['/tmp/build'] },
      credentials: { envVars: [{ name: 'GITHUB_TOKEN', mode: 'deny' }] },
      network: {
        allowedDomains: ['github.com'],
        httpProxyPort: 8080,
        tlsTerminate: {},
      },
      enableWeakerNestedSandbox: false,
    });
    expect(result.success).toBe(true);
  });
});

describe('SettingsHooksSchema', () => {
  it('should accept PreToolUse hooks', () => {
    const result = SettingsHooksSchema.safeParse({
      PreToolUse: [
        {
          matcher: 'Write',
          hooks: [
            {
              type: 'command',
              command: 'echo before',
            },
          ],
        },
      ],
    });
    expect(result.success).toBe(true);
  });

  it('should accept PostToolUse hooks', () => {
    const result = SettingsHooksSchema.safeParse({
      PostToolUse: [
        {
          hooks: [
            {
              type: 'command',
              command: 'echo after',
            },
          ],
        },
      ],
    });
    expect(result.success).toBe(true);
  });

  it('should accept all hook event types', () => {
    const result = SettingsHooksSchema.safeParse({
      PreToolUse: [],
      PostToolUse: [],
      PostToolUseFailure: [],
      PermissionRequest: [],
      Notification: [],
      UserPromptSubmit: [],
      Stop: [],
      SubagentStart: [],
      SubagentStop: [],
      PreCompact: [],
      SessionStart: [],
      SessionEnd: [],
      TeammateIdle: [],
      TaskCompleted: [],
    });
    expect(result.success).toBe(true);
  });

  it('should accept empty hooks object', () => {
    const result = SettingsHooksSchema.safeParse({});
    expect(result.success).toBe(true);
  });

  it('should accept hooks with matcher pattern', () => {
    const result = SettingsHooksSchema.safeParse({
      PostToolUse: [
        {
          matcher: 'Write|Edit',
          hooks: [
            {
              type: 'command',
              command: 'prettier --write $FILE',
            },
          ],
        },
      ],
    });
    expect(result.success).toBe(true);
  });

  it('should accept hooks without matcher', () => {
    const result = SettingsHooksSchema.safeParse({
      PostToolUse: [
        {
          hooks: [
            {
              type: 'command',
              command: 'echo done',
            },
          ],
        },
      ],
    });
    expect(result.success).toBe(true);
  });
});

describe('MarketplaceConfigSchema', () => {
  it('models autoUpdate, the documented entry toggle', () => {
    // "Each marketplace entry also accepts an optional `autoUpdate` Boolean... official
    // Anthropic marketplaces default to `true` and all other marketplaces default to
    // `false`" (docs-baseline/settings.md:821).
    const result = MarketplaceConfigSchema.safeParse({
      source: { source: 'github', repo: 'acme/plugins' },
      autoUpdate: true,
    });
    expect(result.success).toBe(true);
  });

  it('does not model the invented `enabled` toggle', () => {
    // `enabled` appears nowhere on a marketplace entry. The schema is non-strict, so the
    // parse succeeds -- what matters is that the key is STRIPPED, not modelled, so
    // claudelint never blesses a toggle Claude Code ignores.
    const result = MarketplaceConfigSchema.parse({
      source: { source: 'github', repo: 'acme/plugins' },
      enabled: true,
    });

    expect(result).not.toHaveProperty('enabled');
  });

  it('accepts skipLfs on a git-backed source', () => {
    const result = MarketplaceConfigSchema.safeParse({
      source: { source: 'github', repo: 'acme/plugins', skipLfs: true },
    });
    expect(result.success).toBe(true);
  });
});

describe('SettingsSchema — the documented surface', () => {
  it('accepts the documented statusLine object', () => {
    // Was `z.string()`, so the docs' own example was rejected: "expected string, received
    // object". Found by the type-conformance gate the moment `Available settings` was bound.
    const result = SettingsSchema.safeParse({
      statusLine: { type: 'command', command: '~/.claude/statusline.sh' },
    });
    expect(result.success).toBe(true);
  });

  it('accepts the documented teammateMode string', () => {
    // Was `z.boolean()`, so `"auto"` -- the documented example -- was rejected.
    expect(SettingsSchema.safeParse({ teammateMode: 'auto' }).success).toBe(true);
  });

  it('models the documented settings surface, not 23 of 117 keys', () => {
    // 94 documented keys were stripped silently by this non-strict object: a user writing
    // them got no validation, and a typo got no warning.
    const modeled = Object.keys(SettingsSchema.shape);

    expect(modeled.length).toBeGreaterThanOrEqual(110);
    for (const field of ['autoCompactEnabled', 'availableModels', 'agent', 'viewMode', 'voice']) {
      expect(modeled).toContain(field);
    }
  });

  it('accepts every documented strictKnownMarketplaces source type', () => {
    // docs-baseline/settings.md:872 — "The allowlist supports multiple marketplace source
    // types. Most sources use exact matching, while `hostPattern` and `pathPattern` use
    // regex matching against the marketplace host and filesystem path respectively."
    //
    // `pathPattern` was missing from the enum, so the documented example at
    // settings.md:955 — { "source": "pathPattern", "pathPattern": "^/opt/approved/" } —
    // was rejected with "Invalid option".
    const documentedSources = [
      { source: 'github', repo: 'owner/repo' },
      { source: 'git', url: 'https://example.com/x.git' },
      { source: 'url', url: 'https://example.com/m.json' },
      { source: 'npm', package: '@scope/pkg' },
      { source: 'directory', path: '/opt/approved' },
      { source: 'file', path: '/opt/approved/m.json' },
      { source: 'hostPattern', hostPattern: '^github\\.com$' },
      { source: 'pathPattern', pathPattern: '^/opt/approved/' },
    ];

    for (const entry of documentedSources) {
      const result = SettingsSchema.safeParse({ strictKnownMarketplaces: [entry] });
      expect(result.success).toBe(true);
    }
  });

  it('does NOT model the global config keys, which belong in ~/.claude.json', () => {
    // "These settings are stored in `~/.claude.json` rather than `settings.json`. Adding
    // them to `settings.json` will trigger a schema validation error." Modelling them here
    // would assert the opposite of what upstream says.
    const modeled = Object.keys(SettingsSchema.shape);

    for (const globalOnly of ['autoUpdates', 'hasCompletedOnboarding']) {
      expect(modeled).not.toContain(globalOnly);
    }
  });
});
