name: Documentation Update
description: Suggest improvements to documentation
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched for existing documentation issues
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - Getting Started Guide
        - Rule Documentation
        - API Documentation
        - Contributing Guide
        - Configuration Guide
        - Examples
        - CLI Usage
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which file or section needs updating?
      placeholder: "docs/rules/skill-missing-timeout.md"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Typo or grammatical error
        - Inaccurate or outdated information
        - Missing information
        - Confusing explanation
        - Code example error
        - Broken link
        - Formatting issue
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the documentation currently say? (copy/paste or describe)
      placeholder: The documentation currently states...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should it say instead? (be specific)
      placeholder: It should state...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help (screenshots, links, etc.)

  - type: checkboxes
    id: participate
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request to fix this
